CREATE TABLE `blog_articles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`titleAr` varchar(255) NOT NULL,
	`titleEn` varchar(255) NOT NULL,
	`excerptAr` text,
	`excerptEn` text,
	`contentAr` text NOT NULL,
	`contentEn` text NOT NULL,
	`featuredImage` text,
	`category` varchar(100),
	`tags` text,
	`metaDescriptionAr` text,
	`metaDescriptionEn` text,
	`metaKeywords` text,
	`authorId` int,
	`viewCount` int DEFAULT 0,
	`isPublished` boolean NOT NULL DEFAULT false,
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_articles_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_articles_slug_unique` UNIQUE(`slug`)
);
